module.exports = {
    alps: require('./alps'),
    blackpill: require('./blackpill'),
    boxheader: require('./boxheader'),
    button: require('./button'),
    choc: require('./choc'),
    chocmini: require('./chocmini'),
    diode: require('./diode'),
    jstph: require('./jstph'),
    jumper: require('./jumper'),
    mx: require('./mx'),
    mxhole: require('./mxhole'),
    npth: require('./npth'),
    oled: require('./oled'),
    omron: require('./omron'),
    pad: require('./pad'),
    pico: require('./pico'),
    promicro: require('./promicro'),
    rgb: require('./rgb'),
    rotary: require('./rotary'),
    scrollwheel: require('./scrollwheel'),
    slider: require('./slider'),
    trrs: require('./trrs'),
    via: require('./via'),
}